version: '3.3'
services:
  master: 
    image: kodcloud/kodexplorer
    container_name: kodexplorer
    environment:
    volumes:
      - "./.crawlab/master:/root/.crawlab"
    ports:    
      - "80:80"
